// Auto-generated by deploy-clob-testnet script
// WC_PROJECT_ID: get yours FREE at https://cloud.reown.com → Create Project → AppKit
// MetaMask injection works WITHOUT a valid ID; WalletConnect QR requires a real one.
const CONFIG = {
  WC_PROJECT_ID: "b56e18d47c72ab683b10814fe9495694",  // Reown public demo ID — replace for production!
  PREDICTION_MARKET_ADDRESS: "0xe242A02d5846BAD57200622668461B76af06b84C",
  USDT_ADDRESS: "0x03Be2979A1Ab9aCdc99E3de44f7d6CBe2b7cf4d1",
  CHAIN_ID: 97,
  CHAIN_NAME: "BNB Smart Chain Testnet",
  RPC_URL: "https://bsc-testnet-rpc.publicnode.com",
  RPC_URLS: [
    "https://bsc-testnet-rpc.publicnode.com",
    "https://data-seed-prebsc-1-s1.binance.org:8545",
    "https://data-seed-prebsc-2-s1.binance.org:8545",
  ],
  DEPLOY_BLOCK: 93397600,
  BLOCK_EXPLORER: "https://testnet.bscscan.com",

  // Optional: external events indexer (BSCScan-compatible API)
  // Provides full history without RPC block pruning limits.
  // Get a free key at https://testnet.bscscan.com/register
  // Leave EVENTS_API_KEY empty to use RPC fallback only.
  EVENTS_API: "https://api-testnet.bscscan.com/api",
  EVENTS_API_KEY: "",

  // snapshot-hub URL for signed order storage (EIP-712)
  // Override at runtime: window.PolyFactory_snapshotHub = 'http://...'
  SNAPSHOT_HUB_URL: "https://snapshothub.onout.org",
};
